# Generated by Django 4.1.7 on 2023-03-19 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orderconfirmation_delivery_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderconfirmation',
            old_name='address_line_1',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='orderconfirmation',
            old_name='zip_code',
            new_name='zip',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address_line_1',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='zip_code',
            new_name='zip',
        ),
        migrations.RemoveField(
            model_name='orderconfirmation',
            name='city',
        ),
        migrations.RemoveField(
            model_name='orderconfirmation',
            name='country',
        ),
        migrations.RemoveField(
            model_name='orderconfirmation',
            name='state',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='city',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='country',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='state',
        ),
    ]
